In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import confusion_matrix ,classification_report

In [2]:
df = pd.read_csv('fakenews.csv')
df.head()

Unnamed: 0                                              title label
0           0                       You Can Smell Hillary’s Fear  FAKE
1           1  Watch The Exact Moment Paul Ryan Committed Pol...  FAKE
2           2        Kerry to go to Paris in gesture of sympathy  REAL
3           3  Bernie supporters on Twitter erupt in anger ag...  FAKE
4           4   The Battle of New York: Why This Primary Matters  REAL

In [3]:

df['label'] = df['label'].map({'FAKE':1,'REAL':0})
df

Unnamed: 0                                              title  label
0            0                       You Can Smell Hillary’s Fear      1
1            1  Watch The Exact Moment Paul Ryan Committed Pol...      1
2            2        Kerry to go to Paris in gesture of sympathy      0
3            3  Bernie supporters on Twitter erupt in anger ag...      1
4            4   The Battle of New York: Why This Primary Matters      0
..         ...                                                ...    ...
95          95  The Mandela Effect was made by one overlooked ...      1
96          96  CNN: One voter can make a difference by voting...      1
97          97  Give Social Security recipients a CEO-style raise      0
98          98  Fireworks erupt between Trump and Bush, Rubio ...      0
99          99  Obama, sounding like his critics, admits no 'c...      0

[100 rows x 3 columns]

In [4]:
features = df['title'].values
target = df['label'].values

In [5]:
X_train, X_test, Y_train ,Y_test = train_test_split(features,target,test_size=0.2,random_state=65)
vectorizer = TfidfVectorizer(stop_words="english")
X_train_bow = vectorizer.fit_transform(X_train)
X_test_bow = vectorizer.transform(X_test)

In [6]:
results ={'RandomForestClassifier':RandomForestClassifier(n_estimators=7,random_state=0),'LogisticRegression':LogisticRegression(solver='liblinear',max_iter=100),'KNN classifier':KNeighborsClassifier(n_neighbors=2)}
for key ,value in results.items():
    a = value
    a.fit(X_train_bow,Y_train)
    y_predict = a.predict(X_test_bow)
    print(key,"\n")
    print(confusion_matrix(Y_test,y_predict),"\n")
    print(classification_report(Y_test,y_predict),"\n")
    print("The model score on test data:",a.score(X_test_bow,Y_test),"\n\n")
    results[key]= a.score(X_train_bow,Y_train)
print(results)
    


RandomForestClassifier 

[[12  0]
 [ 6  2]] 

              precision    recall  f1-score   support

           0       0.67      1.00      0.80        12
           1       1.00      0.25      0.40         8

    accuracy                           0.70        20
   macro avg       0.83      0.62      0.60        20
weighted avg       0.80      0.70      0.64        20
 

The model score on test data: 0.7 


LogisticRegression 

[[11  1]
 [ 6  2]] 

              precision    recall  f1-score   support

           0       0.65      0.92      0.76        12
           1       0.67      0.25      0.36         8

    accuracy                           0.65        20
   macro avg       0.66      0.58      0.56        20
weighted avg       0.65      0.65      0.60        20
 

The model score on test data: 0.65 




KNN classifier 

[[11  1]
 [ 5  3]] 

              precision    recall  f1-score   support

           0       0.69      0.92      0.79        12
           1       0.75      0.38      0.50         8

    accuracy                           0.70        20
   macro avg       0.72      0.65      0.64        20
weighted avg       0.71      0.70      0.67        20
 

The model score on test data: 0.7 


{'RandomForestClassifier': 0.975, 'LogisticRegression': 1.0, 'KNN classifier': 0.7375}
